### ISSUE TITLE
Latest npm version of redbox-react 1.3.6 doesn't contain TypeScript types.

### ISSUE THREAD

**Issue by derekdon** [commissure/redbox-react#95]
Can you please publish this with the ts types? Thanks!

**Comment by mxlje** [comment]
Hey @derekdon, thanks for bringing this to our attention. Because we used a `chore` commit for #93 a new version was not automatically released, I missed this.

A new version will be published soon (unrelated PR) and that should then publish the changes from #93. I will ping you here once that is live.

**Comment by davidpfahler** [comment]
Has been released as [`v1.3.7`](https://github.com/commissure/redbox-react/releases/tag/v1.3.7)
